ALTER TABLE platos ADD COLUMN IF NOT EXISTS imagen_url TEXT;
ALTER TABLE categorias ADD COLUMN IF NOT EXISTS imagen_url TEXT;
ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS motivo_rechazo TEXT;
ALTER TABLE pedidos ADD COLUMN IF NOT EXISTS notas TEXT;
ALTER TABLE pedidos ADD COLUMN IF NOT EXISTS metodo_pago TEXT;
ALTER TABLE lineas_pedido ADD COLUMN IF NOT EXISTS notas TEXT;